"""analytics drilldown indexes

Revision ID: 30a6b671695c
Revises: 3739ad1dcf6c
Create Date: 2026-07-08 21:15:28.317513

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


revision = '30a6b671695c'
down_revision = '3739ad1dcf6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_figs_block_id'), 'figs', ['block_id'], unique=False)
    op.create_index('ix_yields_stage_month_fig', 'yields', ['stage_id', 'yield_month', 'fig_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_yields_stage_month_fig', table_name='yields')
    op.drop_index(op.f('ix_figs_block_id'), table_name='figs')
    # ### end Alembic commands ###
