"""drop fig total_members column

Revision ID: 3739ad1dcf6c
Revises: 82b4b3356c50
Create Date: 2026-07-08 08:46:05.351466

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


revision = '3739ad1dcf6c'
down_revision = '82b4b3356c50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('figs', 'total_members')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('figs', sa.Column('total_members', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
