"""baseline

Revision ID: 82b4b3356c50
Revises: 
Create Date: 2026-06-24 14:06:49.188324

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


revision = '82b4b3356c50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('castes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caste_name', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caste_name')
    )
    op.create_table('districts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('district_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('state_name', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_name')
    )
    op.create_table('religions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('religion_name', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('religion_name')
    )
    op.create_table('sectors',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sector_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectors_sector_name'), 'sectors', ['sector_name'], unique=True)
    op.create_table('blocks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('district_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('block_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'block_name')
    )
    op.create_index(op.f('ix_blocks_district_id'), 'blocks', ['district_id'], unique=False)
    op.create_table('stages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sector_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('yield_stage_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('output_unit', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_name')
    )
    op.create_index(op.f('ix_stages_sector_id'), 'stages', ['sector_id'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('farmer_code', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('mobile_no', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('aadhaar_no', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('pan_no', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('photo_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_pwd', sa.Boolean(), nullable=False),
    sa.Column('education_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('farmer_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('caste_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('religion_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('family_member_male', sa.Integer(), nullable=False),
    sa.Column('family_member_female', sa.Integer(), nullable=False),
    sa.Column('district_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('village_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('gaon_panchayat', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('post_office', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('police_station', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('pin_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('stage_ids', sa.JSON(), nullable=True),
    sa.Column('primary_stage_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bank_details', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_inactivated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['caste_id'], ['castes.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['religion_id'], ['religions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_aadhaar_no'), 'farmers', ['aadhaar_no'], unique=False)
    op.create_index(op.f('ix_farmers_block_id'), 'farmers', ['block_id'], unique=False)
    op.create_index(op.f('ix_farmers_district_id'), 'farmers', ['district_id'], unique=False)
    op.create_index(op.f('ix_farmers_farmer_code'), 'farmers', ['farmer_code'], unique=True)
    op.create_index(op.f('ix_farmers_mobile_no'), 'farmers', ['mobile_no'], unique=True)
    op.create_table('figs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fig_code', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('fig_name', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('stage_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('district_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('formation_date', sa.Date(), nullable=False),
    sa.Column('panchayat_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_no', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('meeting_venue', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('total_members', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_figs_district_id'), 'figs', ['district_id'], unique=False)
    op.create_index(op.f('ix_figs_fig_code'), 'figs', ['fig_code'], unique=True)
    op.create_table('schemes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheme_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('eligible_farmer_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('total_budget_rs', sa.Float(), nullable=False),
    sa.Column('disbursement_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_name')
    )
    op.create_table('allocations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheme_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('district_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allocated_amount_rs', sa.Float(), nullable=False),
    sa.Column('utilised', sa.Float(), nullable=False),
    sa.Column('remaining', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'district_id')
    )
    op.create_index(op.f('ix_allocations_district_id'), 'allocations', ['district_id'], unique=False)
    op.create_index(op.f('ix_allocations_scheme_id'), 'allocations', ['scheme_id'], unique=False)
    op.create_table('beneficiaries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheme_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('farmer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('district_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('benefit_amount', sa.Float(), nullable=False),
    sa.Column('benefit_material', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('disbursement_date', sa.Date(), nullable=True),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiaries_district_id'), 'beneficiaries', ['district_id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_farmer_id'), 'beneficiaries', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_beneficiaries_scheme_id'), 'beneficiaries', ['scheme_id'], unique=False)
    op.create_table('fig_members',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fig_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('farmer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joining_date', sa.DateTime(), nullable=False),
    sa.Column('exit_date', sa.DateTime(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['fig_id'], ['figs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fig_members_farmer_id'), 'fig_members', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_fig_members_fig_id'), 'fig_members', ['fig_id'], unique=False)
    op.create_table('lands',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('farmer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dag_no', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('patta_no', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('land_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('land_area_sqm', sa.Float(), nullable=True),
    sa.Column('land_area_bigha', sa.Float(), nullable=True),
    sa.Column('land_area_hectare', sa.Float(), nullable=True),
    sa.Column('gps_verified', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('gps_points', sa.JSON(), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('overlap_detected', sa.Boolean(), nullable=False),
    sa.Column('overlapping_parcel_ids', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lands_boundary', 'lands', ['boundary'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_lands_farmer_id'), 'lands', ['farmer_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fig_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meeting_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('meeting_time', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('meeting_venue', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('meeting_details', sa.Text(), nullable=True),
    sa.Column('next_meeting_date', sa.Date(), nullable=True),
    sa.Column('meeting_month', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('submission_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fig_id'], ['figs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fig_id', 'meeting_month')
    )
    op.create_index(op.f('ix_meetings_fig_id'), 'meetings', ['fig_id'], unique=False)
    op.create_index(op.f('ix_meetings_meeting_month'), 'meetings', ['meeting_month'], unique=False)
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mobile_no', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('district_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fig_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('farmer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('lock_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['fig_id'], ['figs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_mobile_no'), 'users', ['mobile_no'], unique=True)
    op.create_table('attendance',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meeting_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fig_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('farmer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['fig_id'], ['figs.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_meeting_id'), 'attendance', ['meeting_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_table('notifications',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('attachment_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('sent_by_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_by_role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('recipient_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stage_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proposed_from_date', sa.Date(), nullable=False),
    sa.Column('proposed_to_date', sa.Date(), nullable=False),
    sa.Column('proposed_venue', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('estimated_participants', sa.Integer(), nullable=False),
    sa.Column('participant_names', sa.Text(), nullable=True),
    sa.Column('requesting_da_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('district_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('approval_from_date', sa.Date(), nullable=True),
    sa.Column('approval_to_date', sa.Date(), nullable=True),
    sa.Column('approved_venue', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('approval_remarks', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('actual_from_date', sa.Date(), nullable=True),
    sa.Column('actual_to_date', sa.Date(), nullable=True),
    sa.Column('actual_venue', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('actual_participants', sa.Integer(), nullable=False),
    sa.Column('completion_report', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['requesting_da_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainings_district_id'), 'trainings', ['district_id'], unique=False)
    op.create_table('yields',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fig_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('farmer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meeting_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('yield_month', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('is_primary_stage', sa.Boolean(), nullable=False),
    sa.Column('planned_yield', sa.Float(), nullable=False),
    sa.Column('actual_yield', sa.Float(), nullable=False),
    sa.Column('next_month_plan', sa.Float(), nullable=False),
    sa.Column('stock_balance', sa.Float(), nullable=False),
    sa.Column('sold_quantity', sa.Float(), nullable=False),
    sa.Column('sold_rate', sa.Float(), nullable=False),
    sa.Column('earning', sa.Float(), nullable=False),
    sa.Column('crop_loss_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('entered_by_role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('submission_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['fig_id'], ['figs.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farmer_id', 'stage_id', 'yield_month')
    )
    op.create_index(op.f('ix_yields_farmer_id'), 'yields', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_yields_fig_id'), 'yields', ['fig_id'], unique=False)
    op.create_index(op.f('ix_yields_stage_id'), 'yields', ['stage_id'], unique=False)
    op.create_index(op.f('ix_yields_yield_month'), 'yields', ['yield_month'], unique=False)
    op.create_table('notification_recipients',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notification_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_recipients_notification_id'), 'notification_recipients', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_recipients_recipient_user_id'), 'notification_recipients', ['recipient_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_recipients_recipient_user_id'), table_name='notification_recipients')
    op.drop_index(op.f('ix_notification_recipients_notification_id'), table_name='notification_recipients')
    op.drop_table('notification_recipients')
    op.drop_index(op.f('ix_yields_yield_month'), table_name='yields')
    op.drop_index(op.f('ix_yields_stage_id'), table_name='yields')
    op.drop_index(op.f('ix_yields_fig_id'), table_name='yields')
    op.drop_index(op.f('ix_yields_farmer_id'), table_name='yields')
    op.drop_table('yields')
    op.drop_index(op.f('ix_trainings_district_id'), table_name='trainings')
    op.drop_table('trainings')
    op.drop_table('notifications')
    op.drop_table('files')
    op.drop_index(op.f('ix_attendance_meeting_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_users_mobile_no'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_meetings_meeting_month'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_fig_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_lands_farmer_id'), table_name='lands')
    op.drop_index('idx_lands_boundary', table_name='lands', postgresql_using='gist')
    op.drop_table('lands')
    op.drop_index(op.f('ix_fig_members_fig_id'), table_name='fig_members')
    op.drop_index(op.f('ix_fig_members_farmer_id'), table_name='fig_members')
    op.drop_table('fig_members')
    op.drop_index(op.f('ix_beneficiaries_scheme_id'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_farmer_id'), table_name='beneficiaries')
    op.drop_index(op.f('ix_beneficiaries_district_id'), table_name='beneficiaries')
    op.drop_table('beneficiaries')
    op.drop_index(op.f('ix_allocations_scheme_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_district_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_table('schemes')
    op.drop_index(op.f('ix_figs_fig_code'), table_name='figs')
    op.drop_index(op.f('ix_figs_district_id'), table_name='figs')
    op.drop_table('figs')
    op.drop_index(op.f('ix_farmers_mobile_no'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_farmer_code'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_district_id'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_block_id'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_aadhaar_no'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_stages_sector_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_blocks_district_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_sectors_sector_name'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_table('religions')
    op.drop_table('districts')
    op.drop_table('castes')
    # ### end Alembic commands ###
