"""The 126 Legislative Assembly Constituencies of Assam, per the ECI's final delimitation
order of 11 August 2023, mapped to the district each one sits in.

A Sericulture Circle is mapped to its LAC by the State Admin; this list is what that
dropdown offers. It replaces the old Sub-division Office / CDC master.

Three reconciliations were needed between the published table and this app's district
master, each checked rather than assumed:

  * "Sibsagar" is spelt "Sivasagar" in our district master — same district.
  * "Karimganj" district was renamed "Sribhumi" in 2024; our master carries the new name,
    so LACs 123-126 are mapped to Sribhumi. The constituency names themselves are
    unchanged and still read "Karimganj North/South".
  * The published table lists Rangiya (31) and Kamalpur (32) under "Darrang-Udalguri",
    which is the *parliamentary* constituency, not a district. Both sit in Kamrup
    district, which is how they are mapped here.

Constituency names use a plain hyphen rather than the en-dash of the official gazette, so
they can be typed and searched from an ordinary keyboard.
"""

# (number, name, district as named in this app's district master)
ASSAM_LACS: list[tuple[int, str, str]] = [
    (1, "Gossaigaon", "Kokrajhar"),
    (2, "Dotma", "Kokrajhar"),
    (3, "Kokrajhar", "Kokrajhar"),
    (4, "Baokhungri", "Kokrajhar"),
    (5, "Parbatjhora", "Kokrajhar"),
    (6, "Golakganj", "Dhubri"),
    (7, "Gauripur", "Dhubri"),
    (8, "Dhubri", "Dhubri"),
    (9, "Birsing Jarua", "Dhubri"),
    (10, "Bilasipara", "Dhubri"),
    (11, "Mankachar", "South Salmara-Mankachar"),
    (12, "Jaleshwar", "Goalpara"),
    (13, "Goalpara West", "Goalpara"),
    (14, "Goalpara East", "Goalpara"),
    (15, "Dudhnai", "Goalpara"),
    (16, "Abhayapuri", "Bongaigaon"),
    (17, "Srijangram", "Bongaigaon"),
    (18, "Bongaigaon", "Bongaigaon"),
    (19, "Sidli-Chirang", "Chirang"),
    (20, "Bijni", "Chirang"),
    (21, "Bhowanipur-Sorbhog", "Bajali"),
    (22, "Mandia", "Barpeta"),
    (23, "Chenga", "Barpeta"),
    (24, "Barpeta", "Barpeta"),
    (25, "Pakabetbari", "Barpeta"),
    (26, "Bajali", "Bajali"),
    (27, "Chamaria", "Kamrup"),
    (28, "Boko-Chaygaon", "Kamrup"),
    (29, "Palasbari", "Kamrup"),
    (30, "Hajo-Sualkuchi", "Kamrup"),
    (31, "Rangiya", "Kamrup"),
    (32, "Kamalpur", "Kamrup"),
    (33, "Dispur", "Kamrup Metropolitan"),
    (34, "Dimoria", "Kamrup Metropolitan"),
    (35, "New Guwahati", "Kamrup Metropolitan"),
    (36, "Guwahati Central", "Kamrup Metropolitan"),
    (37, "Jalukbari", "Kamrup Metropolitan"),
    (38, "Barkhetri", "Nalbari"),
    (39, "Nalbari", "Nalbari"),
    (40, "Tihu", "Nalbari"),
    (41, "Manas", "Baksa"),
    (42, "Baksa", "Baksa"),
    (43, "Tamulpur", "Tamulpur"),
    (44, "Goreshwar", "Tamulpur"),
    (45, "Bhergaon", "Udalguri"),
    (46, "Udalguri", "Udalguri"),
    (47, "Majbat", "Udalguri"),
    (48, "Tangla", "Udalguri"),
    (49, "Sipajhar", "Darrang"),
    (50, "Mangaldai", "Darrang"),
    (51, "Dalgaon", "Darrang"),
    (52, "Jagiroad", "Morigaon"),
    (53, "Laharighat", "Morigaon"),
    (54, "Morigaon", "Morigaon"),
    (55, "Dhing", "Nagaon"),
    (56, "Rupohihat", "Nagaon"),
    (57, "Kaliabor", "Nagaon"),
    (58, "Samaguri", "Nagaon"),
    (59, "Barhampur", "Nagaon"),
    (60, "Nagaon-Batadraba", "Nagaon"),
    (61, "Raha", "Nagaon"),
    (62, "Binnakandi", "Hojai"),
    (63, "Hojai", "Hojai"),
    (64, "Lumding", "Hojai"),
    (65, "Dhekiajuli", "Sonitpur"),
    (66, "Barchalla", "Sonitpur"),
    (67, "Tezpur", "Sonitpur"),
    (68, "Rangapara", "Sonitpur"),
    (69, "Nadaur", "Sonitpur"),
    (70, "Biswanath", "Biswanath"),
    (71, "Behali", "Biswanath"),
    (72, "Gohpur", "Biswanath"),
    (73, "Bihpuria", "Lakhimpur"),
    (74, "Rongonadi", "Lakhimpur"),
    (75, "Naoboicha", "Lakhimpur"),
    (76, "Lakhimpur", "Lakhimpur"),
    (77, "Dhakuakhana", "Lakhimpur"),
    (78, "Dhemaji", "Dhemaji"),
    (79, "Sissiborgaon", "Dhemaji"),
    (80, "Jonai", "Dhemaji"),
    (81, "Sadiya", "Tinsukia"),
    (82, "Doom Dooma", "Tinsukia"),
    (83, "Margherita", "Tinsukia"),
    (84, "Digboi", "Tinsukia"),
    (85, "Makum", "Tinsukia"),
    (86, "Tinsukia", "Tinsukia"),
    (87, "Chabua-Lahowal", "Dibrugarh"),
    (88, "Dibrugarh", "Dibrugarh"),
    (89, "Khowang", "Dibrugarh"),
    (90, "Duliajan", "Dibrugarh"),
    (91, "Tingkhong", "Dibrugarh"),
    (92, "Naharkatia", "Dibrugarh"),
    (93, "Sonari", "Charaideo"),
    (94, "Mahmora", "Charaideo"),
    (95, "Demow", "Sivasagar"),
    (96, "Sibsagar", "Sivasagar"),
    (97, "Nazira", "Sivasagar"),
    (98, "Majuli", "Majuli"),
    (99, "Teok", "Jorhat"),
    (100, "Jorhat", "Jorhat"),
    (101, "Mariani", "Jorhat"),
    (102, "Titabor", "Jorhat"),
    (103, "Golaghat", "Golaghat"),
    (104, "Dergaon", "Golaghat"),
    (105, "Bokakhat", "Golaghat"),
    (106, "Khumtai", "Golaghat"),
    (107, "Sarupathar", "Golaghat"),
    (108, "Bokajan", "Karbi Anglong"),
    (109, "Howraghat", "Karbi Anglong"),
    (110, "Diphu", "Karbi Anglong"),
    (111, "Rongkhang", "West Karbi Anglong"),
    (112, "Amri", "West Karbi Anglong"),
    (113, "Haflong", "Dima Hasao"),
    (114, "Lakhipur", "Cachar"),
    (115, "Udharbond", "Cachar"),
    (116, "Katigorah", "Cachar"),
    (117, "Borkhola", "Cachar"),
    (118, "Silchar", "Cachar"),
    (119, "Sonai", "Cachar"),
    (120, "Dholai", "Cachar"),
    (121, "Hailakandi", "Hailakandi"),
    (122, "Algapur-Katlicherra", "Hailakandi"),
    (123, "Karimganj North", "Sribhumi"),
    (124, "Karimganj South", "Sribhumi"),
    (125, "Patharkandi", "Sribhumi"),
    (126, "Ram Krishna Nagar", "Sribhumi"),
]

assert len(ASSAM_LACS) == 126, f"expected 126 constituencies, got {len(ASSAM_LACS)}"
assert [n for n, _, _ in ASSAM_LACS] == list(range(1, 127)), "constituency numbers must be 1..126"
